dist:     xenial
sudo:     required

language: cpp
cache: cargo

os:
    - linux

compiler:
    - gcc
    - Clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
    - git ls-files sourcs/src/ | xargs clang-format -i && git diff --exit-code
    - sudo apt-get install libncursesw5-dev
    - make
    - bin/Keyboard-Ninja-test
    
before_install:
    - eval "${MATRIX_EVAL}"